### ISSUE TITLE
API requests for campaigns and protocol metadata

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergofund#2]
* make API request for getting ErgoFund-related NFT and box ids, campaign registration price and reward script \
* make API request to read all the campaigns (with pagination)

**Comment by ezi0-audit0re** [comment]
On it.
Added an API endpoint in #3 for campaings: `localhost:3000/campaings`

After doing #4, we can provide full campaign data through the mentioned endpoint.

**Comment by ezi0-audit0re** [comment]
Done in #6 .
